FROM jenkins/jenkins:lts-jdk21

USER root

# 🔥 install docker properly
RUN apt-get update && \
    apt-get install -y docker.io && \
    apt-get clean

# 🔥 fix permission
RUN usermod -aG docker jenkins

USER jenkins